name: applied-category-theory-course
version: 0.1
synopsis: A project for applied category. 
description: Learning project 
maintainer: Group 
github: grant/applied-category-theory-course 
category: Development
extra-source-files:
  - CHANGELOG.md
ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- HaskellForMaths == 0.4.*
- containers >= 0.5.0.0 && < 0.7.0.0

library:
  source-dirs: src

executables:
  applied-category-theory-course-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied-category-theory-course

tests:
  applied-category-theory-course-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - applied-category-theory-course
